### ISSUE TITLE
Add Audit Log Module

### ISSUE THREAD

**Issue by brianghig** [bluehalo/ngx-starter#13]
Provide an Audit log module that allows a user with the “auditor” role to view and search audit entries returned from the server endpoint(s).

**Comment by brianghig** [comment]
@jrassa has your team started on this? If not, we're going to give it a shot.

**Comment by jrassa** [comment]
Not yet.

**Comment by brianghig** [comment]
Resolving per #74

**Comment by brianghig** [comment]
Closed per #74 and #76
