### ISSUE TITLE
Migrate from tslint → eslint

### ISSUE THREAD

**Issue by tzfx** [bluehalo/ngx-starter#130]
I think we've mentioned this before, but I wanted to put up an issue just to start the discussion.

TSLint has been deprecated and the maintainers have made known their intention to move to eslint entirely, with the [typescript-eslint](https://github.com/typescript-eslint/typescript-eslint/) project.

We should probably look at how feasible it would be to make the migration.

Some resources:

- https://github.com/typescript-eslint/tslint-to-eslint-config Migration config
- https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/ROADMAP.md Support roadmap comparing tslint rules to their eslint equivalents
- https://medium.com/palantir/tslint-in-2019-1a144c2317a9 Rationale by the main tslint maintainer on the shift.

**Comment by jrassa** [comment]
https://github.com/angular/angular-cli/issues/13732#issuecomment-573149865

Official support from angular may come with Angular 10.

**Comment by jrassa** [comment]
Migration to eslint was completed in #233

**Comment by tzfx** [comment]
# 👏 👏
