### ISSUE TITLE
Mouse-over visuals on the Audit ‘View Details' link

### ISSUE THREAD

**Issue by sshah-asymmetrik** [bluehalo/ngx-starter#162]
**Current Behavior:**
When I hover my mouse over the link, it either stays a normal cursor (on the eye icon) or turns to a text-selection ‘I’ cursor on the text part. There's nothing exactly wrong with that, but I think we could improve it to make it more apparent to the user that it's a clickable link.

**Desired Behavior:**
- Have the mouse instead turn into the ‘mickey mouse' looking glove like it does when hovering over the checkboxes on the left side of the page
- Highlight/change color of/underline the text when it’s being hovered on

**Comment by jrassa** [comment]
This has been fixed.
