### ISSUE TITLE
Audit 'View Details' close 'X' icon location

### ISSUE THREAD

**Issue by sshah-asymmetrik** [bluehalo/ngx-starter#163]
**Current behavior:**
Currently, in the modal that pops up for audit details, the 'X' icon gets smashed onto the end of the title of the modal.

**Desired behavior:**
Right-align the 'X' icon.

**Comment by tzfx** [comment]
@sshah-asymmetrik Is this fixed with the new unified asym-modal behaviour?

**Comment by jrassa** [comment]
Looks like this has been fixed.
