### ISSUE TITLE
Redirect endless loop introduced in #171

### ISSUE THREAD

**Issue by jrassa** [bluehalo/ngx-starter#191]
@tnguyenasym I think I discovered an endless loop introduced in #171.

User is redirected to the unauthorized page due to missing roles.  Once on unauthorized page, there are no required roles, so there are no missing roles, the user is then redirected back to homepage.  If homepage has required roles,  as it does in the starter, they will then be redirected back again to unauthorized and the loop repeats.

I am disabling for now in #189.

**Comment by brianghig** [comment]
@jrassa @tnguyenasym this is resolved now, right?

**Comment by jrassa** [comment]
I commented out the offending code.  I am not sure if the intended functionality of that code can be achieved without causing the loop.  I created the ticket to highlight the issue.  Not sure if there is anything else to be done.
