### ISSUE TITLE
Create `asy-modal` content wrapper

### ISSUE THREAD

**Issue by sshah-asymmetrik** [bluehalo/ngx-starter#196]
Create a wrapper component that contains the standard pieces of a modal and allows us to insert modal content into it.

As per @jrassa's design, it's usage would look something like this:
```
<asy-modal title="Give Feedback" okText="Submit" cancelText="Cancel" (ok)="onOk()" (cancel)="onCancel" [disableOk]="!submitFeedbackForm.form.valid">
  <!-- modal body content goes here -->
  <form>
  </form>
</asy-modal>
```

This should be used in both the `modal.component` and `contianer-modal` component, which currently both contain redundant header/footer content.

**Comment by jrassa** [comment]
I'm going to work on this.

**Comment by tzfx** [comment]
Looks like this is done? Closing out the issue! @jrassa
