### ISSUE TITLE
Navbar notification container is too small

### ISSUE THREAD

**Issue by brianghig** [bluehalo/ngx-starter#197]
The container for notifications / messages coming from the nav bar is too small to properly render any notifications inline. In order to read these, it forces the user to navigate to the messages page. We should improve the styling / width to be able to render a full notification.

<img width="332" alt="Screen Shot 2021-04-06 at 9 36 23 AM" src="https://user-images.githubusercontent.com/297404/113719427-98b54780-96bb-11eb-9d85-003a3115ee0a.png">

**Comment by tzfx** [comment]
Agreed. I think we can push the overall width a good bit wider to accommodate more text, along with allowing wrapping of text instead of the hard hidden overflow that we currently have going. Over a certain point of *verticality*/content it may make sense to ellipsisize the overflow.
