### ISSUE TITLE
Audit.actor index is receiving the user object instead of an expected string

### ISSUE THREAD

**Issue by tnguyenasym** [bluehalo/ngx-starter#201]
The `audit` collection is expecting an `audit.actor` string in the Mongoose model but receives the whole user object instead. About two months ago, this wasn't a problem because it was a text index, but since it was changed to a normal index, mongo will present this error on trying to index that field:

`Error trying to persist audit record to storage. (err.code=17280)`
`MongoError: WiredTigerIndex::insert: key too large to index, failing`

**Comment by brianghig** [comment]
Resolved per https://github.com/bluehalo/node-rest-starter/pull/129
