### ISSUE TITLE
Add styling to admin filters

### ISSUE THREAD

**Issue by brianghig** [bluehalo/ngx-starter#25]
The Admin Users and EUA listings have unstyled Column selectors and quick filters. Let's add a baseline styling that provides a consistent branding and UX design.

**Comment by brianghig** [comment]
@jrassa @ymao1 do we have any default styling that we can bring over for these left-hand filters?

**Comment by jrassa** [comment]
@brianghig I am working on updating some stuff with the filters now.  I will include better default styling.

**Comment by brianghig** [comment]
Thanks @jrassa ! Feel free to assign this issue to yourself if you'd like. I'm working on #19 at the moment.

**Comment by jrassa** [comment]
Resolved by #28
