### ISSUE TITLE
Upgrade to Bootstrap 5

### ISSUE THREAD

**Issue by brianghig** [bluehalo/ngx-starter#267]
Bootstrap 5 was released about a year ago and contains a few big optimizations, like the removal of the popper.js and jquery dependencies. This should reduce the overall size of the UI bundle while staying current with an actively maintained framework. 

- Upgrade bootstrap to v5, updating component templates as needed
- Remove popper.js dependency
- Remove jquery dependency

**Comment by jrassa** [comment]
closed via #380
