### ISSUE TITLE
fresh clone, and attempting to start throws API Error 500

### ISSUE THREAD

**Issue by bsampica** [bluehalo/ngx-starter#370]
When attempting to start the app for the first time:
git clone [url]
npm install
npm run start

The application loader shows with the angular symbol, and eventually fails with this:
`GET http://localhost:4200/api/config 500 (Internal Server Error)`

I've updated my proxy.conf.json to look like this:

`{
  "/api/*": {
    "target": "http://localhost:4200",
    "secure": false,
    "logLevel": "debug",
    "changeOrigin": true
  },
  "/socket.io/*": {
    "target": "http://localhost:4200",
    "secure": false,
    "ws": true
  }
}`

I've also started it using ng serve --proxy-config proxy.conf.json with the same result.  
Where does it get the app config from?

**Comment by jrassa** [comment]
This project is designed to run alongside https://github.com/bluehalo/node-rest-starter.

**Comment by bsampica** [comment]
Ahhh!  And that would make perfect sense.  :)   You should throw that in your quickstart readme.
Thank you, great work on this by the way.  I appreciate the quick response.
