### ISSUE TITLE
Maintain session after login

### ISSUE THREAD

**Issue by brianghig** [bluehalo/ngx-starter#8]
The current starter requires the user to login (by directing them to the /signin page) on each page refresh. We should check if the user is already authenticated with any stored credentials in order to make this process smoother.

**Comment by brianghig** [comment]
@jrassa @reblace @mheir @matthewgaulin @ymao1 any thoughts / preferences on how we should persist a user's authentication across multiple logins for username/password `local` authentication? Our previous versions relied on the "User" object being set in the returned HTML template.

For context, `signin.component.ts` handles this for `proxy-pki` mode by making the request to `auth/signin` just after the config is returned.

**Comment by brianghig** [comment]
@reblace how are you liking the work on the `feature/authControls` branch with regards to authentication and routing?

**Comment by reblace** [comment]
@brianghig The following are things we need to work related to auth controls:

- HttpInterceptor that reacts to the loss of session or other access control failure
- AuthGuard that controls access to routes
- Detailed auth error messages
- JWT support, and store JWT token and user state in local storage
- Decide what to do with the config load. It's currently in the App Initializer, but maybe we should move it to a "Loading/Bootstrapping" component
- Login/Signup page

What do you think? We could branch off of `feature/authControls` branch for each of the above. Or, start with a new clean branch and pull over stuff as appropriate. Or, we could do these each on their own branch off of develop.

**Comment by brianghig** [comment]
@reblace looks like `feature/authControls` is a good branch to start from. It seems that we could deprioritize the JWT work and the Loading/Bootstrapping component in favor of the others (i.e., HttpInterceptor, AuthGuard, and Login/Signup page), in order to show meaningful progress in the short term. Do you think that would work architecturally, or does it make more sense to do them all in one effort?

**Comment by brianghig** [comment]
@jrassa @reblace I think this ticket should be next on our list of priorities, since most of the functionality we're building will depend on these authorization checks being in place. Hopefully it's easier to exercise now that we can add EUAs again via the UI.

**Comment by jrassa** [comment]
I have merged `develop` into `feature/authControls` and made some updates so that the session is maintained when the page is reloaded.  The next thing I was going to to look at is locking down routes.
I was considering trying out [ngx-permissions](https://github.com/AlexKhymenko/ngx-permissions).  Does anyone have any objections?

**Comment by reblace** [comment]
@jrassa Did you see how the existing AuthGuard in the branch works? You can add required roles to route definitions and the AuthGuard can react when someone tries to go to a route they aren't supposed to. It's also how we respond when someone is navigating to a protected route when a login or EUA is required.

**Comment by jrassa** [comment]
@reblace I've seen and understand how the existing AuthGuard works.  I wasn't sure if this was one of those things where we roled our own solution because there was nothing available at the time.  Mainly, looking for feedback if ngx-permissions was worth exploring or if we should just stick with our current approach.

**Comment by brianghig** [comment]
@jrassa @reblace it seems like `ngx-permissions` provides quite a bit of functionality that we don't have yet. Most of their documentation is still in their GitHub README at https://github.com/AlexKhymenko/ngx-permissions vs. their wiki. Beyond a more extensible AuthGuard (as NgxPermissionsGuard), it provides some clever directives that make hiding, showing, and reasoning about permissions fairly declarative within the template. I'd be game for exploring this more as a replacement.

**Comment by jrassa** [comment]
@reblace @brianghig For now I am going to continue working with what we have and have pushed another update.  I took a bit of inspiration from ngx-permissions.  In the previous starter a lot of the logic for checking roles was contained in the user model.  I created an authorization service to encapsulate these as well as access to the session.  That way components can check roles in a more decoupled fashion.  I also created an authorization directive which is being used in the site navbar.

**Comment by reblace** [comment]
@jrassa +1 to the auth service. Be careful to make sure you are building it to avoid circular dependencies. The big hang up is usually the HttpInterceptor requiring the SessionService which includes a service wrapping the auth REST calls, which requires the HttpInterceptor. If you run into this issue, let's talk cause there are strategies for dealing with it.

@brianghig I agree with trying out `ngx-permissions`. When I looked at their docs, it didn't look like that had that much functionality, but I might have been looking at the wrong thing.\
